version: '3.8'
services:
  node:
    build:
      context: .
      dockerfile: ./compose/develop/Dockerfile
    ports:
      - "5500:5500"
    container_name: backend
    depends_on:
      - mysql
      - redis
    env_file:
      - ./.envs/.develop/.node
    environment:
      - REDIS_HOST=redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: ${ECOMMERCE_MYSQL_NAME}
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=trip
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
