version: '3.8'
services:
  node:
    build:
      context: .
      dockerfile: ./compose/develop/Dockerfile
    ports:
      - "5500:5500"
    container_name: backend
    depends_on:
      - postgres
    env_file:
      - ./.envs/.develop/.node
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .envs/.develop/.mysql
    volumes:
      - postgres-data:/var/lib/postgresql/data
  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - node
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
volumes:
  postgres-data:
